version: '3.3'

services:

  spring:
    image: openjdk:17-alpine
    volumes:
      - '${PWD}:/app'
      - '~/.m2:/root/.m2'
    working_dir: /app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: ./mvnw spring-boot:run